### ISSUE TITLE
Fetch single repo programmatically instead of crawling all

### ISSUE THREAD

**Issue by bonndan** [societe-generale/github-crawler#110]
## Summary

In Java I want the crawler to fetch a single repo and return the findings for it as response.

## Type of Issue

It is a : 
 - [ ] bug
 - [x] request
 - [x] question regarding the documentation

## Motivation

In my usecase I have a repo url and I want all the data from the crawler for that url 

## Current Behavior

As far as I have understood from the getting started project, I can only launch the crawler and then have the output filled somehow (I totally didn't get that).

## Expected Behavior

```java

GitHubCrawlerOutput output = crawler.getOutputFor(myRepoUrl);
```

**Comment by vincent-fuchs** [comment]
I don't think you'll be able to do that directly. the entry point is here : https://github.com/societe-generale/github-crawler/blob/master/github-crawler-core/src/main/kotlin/com/societegenerale/githubcrawler/GitHubCrawler.kt#L32 . what you would be interested in is probably [fetchAndParseRepoContent(repositoriesFromOrga: Set<Repository>)](https://github.com/societe-generale/github-crawler/blob/master/github-crawler-core/src/main/kotlin/com/societegenerale/githubcrawler/GitHubCrawler.kt#L68) method, but it's private.

But I think there's one possibility for you : 

- the list of repositories is first fetched [here](https://github.com/societe-generale/github-crawler/blob/master/github-crawler-core/src/main/kotlin/com/societegenerale/githubcrawler/GitHubCrawler.kt#L48) . 

- So what you could do is implement a very basic version of [RemoteSourceControl ](https://github.com/societe-generale/github-crawler/blob/master/github-crawler-core/src/main/kotlin/com/societegenerale/githubcrawler/remote/RemoteSourceControl.kt), or even subclass one of the existing implementations, and simply override [fun fetchRepositories(organizationName: String): Set<Repository>](https://github.com/societe-generale/github-crawler/blob/master/github-crawler-core/src/main/kotlin/com/societegenerale/githubcrawler/remote/RemoteSourceControl.kt#L34), so that it returns a Set of  a single element, ie the repository you are interested in.

- you can then build a GitHubCrawler instance, passing this custom  RemoteSourceControl and the rest of the configuration, then call `crawl() `  on it, and see where that gets you.

**Comment by bonndan** [comment]
This issue can be closed. I don't need single repo fetching anymore, but thanks a lot for the kind support.
